### ISSUE TITLE
[2018.04] Daily cronjob throws fatal error

### ISSUE THREAD

**Issue by Quix0r** [aimeos/aimeos-laravel#239]
The daily cronjob as mentinued in #238 is throwing a fatal error message:
````
Number of apostrophes don't match: 
					SELECT mpro."id" AS "product.id", mpro."siteid" AS "product.siteid",
						mpro."typeid" AS "product.typeid", mpro."code" AS "product.code",
						mpro."label" AS "product.label", mpro."config" AS "product.config",
						mpro."start" AS "product.datestart", mpro."end" AS "product.dateend",
						mpro."status" AS "product.status", mpro."ctime" AS "product.ctime",
						mpro."mtime" AS "product.mtime", mpro."editor" AS "product.editor",
						mpro."target" AS "product.target"
					FROM "mshop_product" AS mpro
					
					WHERE ( mpro."siteid" IN (1) AND mpro."code" IN ('alias ..=\"cd ..\"','alias ...=\"cd ../..\"','alias h=\'cd ~\'','alias c=\'clear\'','alias art=artisan','alias phpspec=\'vendor/bin/phpspec\'','alias phpunit=\'vendor/bin/phpunit\'','alias serve=serve-laravel','alias xoff=\'sudo phpdismod -s cli xdebug\'','alias xon=\'sudo phpenmod -s cli xdebug\'','alias nrd=\"npm run dev\"','alias nrw=\"npm run watch\"','alias nrww=\"npm run watch-poll\"','alias nrh=\"npm run hot\"','alias nrp=\"npm run production\"','alias yrd=\"yarn run dev\"','alias yrw=\"yarn run watch\"','alias yrwp=\"yarn run watch-poll\"','alias yrh=\"yarn run hot\"','alias yrp=\"yarn run production\"','function artisan() {','    php artisan \"$@\"','}','function dusk() {','    pids=$(pidof /usr/bin/Xvfb)','    if [ ! -n \"$pids\" ]; then','        Xvfb :0 -screen 0 1280x960x24 &','    fi','    php artisan dusk \"$@\"','function php56() {','    sudo update-alternatives --set php /usr/bin/php5.6','function php70() {','    sudo update-alternatives --set php /usr/bin/php7.0','function php71() {','    sudo update-alternatives --set php /usr/bin/php7.1','function php72() {','    sudo update-alternatives --set php /usr/bin/php7.2','function serve-apache() {','    if [[ \"$1\" && \"$2\" ]]','    then','        sudo bash /vagrant/scripts/create-certificate.sh \"$1\"','        sudo dos2unix /vagrant/scripts/serve-apache.sh','        sudo bash /vagrant/scripts/serve-apache.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','    else','        echo \"Error: missing required parameters.\"','        echo \"Usage: \"','        echo \"  serve-apache domain path\"','function serve-laravel() {','        sudo dos2unix /vagrant/scripts/serve-laravel.sh','        sudo bash /vagrant/scripts/serve-laravel.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve domain path\"','function serve-proxy() {','        sudo dos2unix /vagrant/scripts/serve-proxy.sh','        sudo bash /vagrant/scripts/serve-proxy.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-proxy domain port\"','function serve-silverstripe() {','        sudo dos2unix /vagrant/scripts/serve-silverstripe.sh','        sudo bash /vagrant/scripts/serve-silverstripe.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-silverstripe domain path\"','function serve-spa() {','  if [[ \"$1\" && \"$2\" ]]','  then','    sudo bash /vagrant/scripts/create-certificate.sh \"$1\"','    sudo dos2unix /vagrant/scripts/serve-spa.sh','    sudo bash /vagrant/scripts/serve-spa.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','  else','    echo \"Error: missing required parameters.\"','    echo \"Usage: \"','    echo \"  serve-spa domain path\"','  fi','function serve-statamic() {','        sudo dos2unix /vagrant/scripts/serve-statamic.sh','        sudo bash /vagrant/scripts/serve-statamic.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-statamic domain path\"','function serve-symfony2() {','        sudo dos2unix /vagrant/scripts/serve-symfony2.sh','        sudo bash /vagrant/scripts/serve-symfony2.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-symfony2 domain path\"','function serve-symfony4() {','        sudo dos2unix /vagrant/scripts/serve-symfony4.sh','        sudo bash /vagrant/scripts/serve-symfony4.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-symfony4 domain path\"','function serve-pimcore() {','        sudo dos2unix /vagrant/scripts/serve-pimcore.sh','        sudo bash /vagrant/scripts/serve-pimcore.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-pimcore domain path\"','function share() {','    if [[ \"$1\" ]]','        ngrok http ${@:2} -host-header=\"$1\" 80','        echo \"  share domain\"','        echo \"Invocation with extra params passed directly to ngrok\"','        echo \"  share domain -region=eu -subdomain=test1234\"','function flip() {','    sudo bash /vagrant/scripts/flip-webserver.sh','function __has_pv() {','    $(hash pv 2>/dev/null);','    return $?','function __pv_install_message() {','    if ! __has_pv; then','        echo $1','        echo \"Install pv with \\`sudo apt-get install -y pv\\` then run this command again.\"','        echo \"\"','function dbexport() {','    FILE=${1:-/vagrant/mysqldump.sql.gz}','    # This gives an estimate of the size of the SQL file','    # It appears that 80% is a good approximation of','    # the ratio of estimated size to actual size','    SIZE_QUERY=\"select ceil(sum(data_length) * 0.8) as size from information_schema.TABLES\"','    __pv_install_message \"Want to see export progress?\"','    echo \"Exporting databases to \'$FILE\'\"','    if __has_pv; then','        ADJUSTED_SIZE=$(mysql --vertical -uhomestead -psecret -e \"$SIZE_QUERY\" 2>/dev/null | grep \'size\' | awk \'{print $2}\')','        HUMAN_READABLE_SIZE=$(numfmt --to=iec-i --suffix=B --format=\"%.3f\" $ADJUSTED_SIZE)','        echo \"Estimated uncompressed size: $HUMAN_READABLE_SIZE\"','        mysqldump -uhomestead -psecret --all-databases --skip-lock-tables 2>/dev/null | pv  --size=$ADJUSTED_SIZE | gzip > \"$FILE\"','        mysqldump -uhomestead -psecret --all-databases --skip-lock-tables 2>/dev/null | gzip > \"$FILE\"','    echo \"Done.\"','function dbimport() {','    __pv_install_message \"Want to see import progress?\"','    echo \"Importing databases from \'$FILE\'\"','        pv \"$FILE\" --progress --eta | zcat | mysql -uhomestead -psecret 2>/dev/null','        cat \"$FILE\" | zcat | mysql -uhomestead -psecret 2>/dev/null','function xphp() {','    (php -m | grep -q xdebug)','    if [[ $? -eq 0 ]]','        XDEBUG_ENABLED=true','        XDEBUG_ENABLED=false','    if ! $XDEBUG_ENABLED; then xon; fi','    php \\','        -dxdebug.remote_host=192.168.10.1 \\','        -dxdebug.remote_autostart=1 \\','$@','    if ! $XDEBUG_ENABLED; then xoff; fi') )
					GROUP BY mpro."id", mpro."siteid", mpro."typeid", mpro."code",
						mpro."label", mpro."config", mpro."start", mpro."end",
						mpro."status", mpro."ctime", mpro."mtime", mpro."editor",
						mpro."target"
						
					
					LIMIT 133 OFFSET 0
				#0 /home/vagrant/code/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(69): Aimeos\Controller\Jobs\Product\Import\Csv\Standard->run()
#1 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\{closure}(Object(Aimeos\MShop\Context\Item\Standard), Object(Aimeos\Bootstrap), 'product/import/...')
#2 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(171): call_user_func_array(Object(Closure), Array)
#3 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(111): Aimeos\MW\Process\Pcntl->exec(Object(Closure), Array)
#4 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Decorator/Check.php(61): Aimeos\MW\Process\Pcntl->start(Object(Closure), Array, true)
#5 /home/vagrant/code/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(72): Aimeos\MW\Process\Decorator\Check->start(Object(Closure), Array, true)
#6 [internal function]: Aimeos\Shop\Command\JobsCommand->handle()
#7 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#8 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#10 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#11 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(184): Illuminate\Container\Container->call(Array)
#12 /home/vagrant/code/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(171): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /home/vagrant/code/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/vagrant/code/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Aimeos\Shop\Command\JobsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/vagrant/code/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/code/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}Number of apostrophes don't match: 
					SELECT mpro."id" AS "product.id", mpro."siteid" AS "product.siteid",
						mpro."typeid" AS "product.typeid", mpro."code" AS "product.code",
						mpro."label" AS "product.label", mpro."config" AS "product.config",
						mpro."start" AS "product.datestart", mpro."end" AS "product.dateend",
						mpro."status" AS "product.status", mpro."ctime" AS "product.ctime",
						mpro."mtime" AS "product.mtime", mpro."editor" AS "product.editor",
						mpro."target" AS "product.target"
					FROM "mshop_product" AS mpro
					
					WHERE ( mpro."siteid" IN (1) AND mpro."code" IN ('alias ..=\"cd ..\"','alias ...=\"cd ../..\"','alias h=\'cd ~\'','alias c=\'clear\'','alias art=artisan','alias phpspec=\'vendor/bin/phpspec\'','alias phpunit=\'vendor/bin/phpunit\'','alias serve=serve-laravel','alias xoff=\'sudo phpdismod -s cli xdebug\'','alias xon=\'sudo phpenmod -s cli xdebug\'','alias nrd=\"npm run dev\"','alias nrw=\"npm run watch\"','alias nrww=\"npm run watch-poll\"','alias nrh=\"npm run hot\"','alias nrp=\"npm run production\"','alias yrd=\"yarn run dev\"','alias yrw=\"yarn run watch\"','alias yrwp=\"yarn run watch-poll\"','alias yrh=\"yarn run hot\"','alias yrp=\"yarn run production\"','function artisan() {','    php artisan \"$@\"','}','function dusk() {','    pids=$(pidof /usr/bin/Xvfb)','    if [ ! -n \"$pids\" ]; then','        Xvfb :0 -screen 0 1280x960x24 &','    fi','    php artisan dusk \"$@\"','function php56() {','    sudo update-alternatives --set php /usr/bin/php5.6','function php70() {','    sudo update-alternatives --set php /usr/bin/php7.0','function php71() {','    sudo update-alternatives --set php /usr/bin/php7.1','function php72() {','    sudo update-alternatives --set php /usr/bin/php7.2','function serve-apache() {','    if [[ \"$1\" && \"$2\" ]]','    then','        sudo bash /vagrant/scripts/create-certificate.sh \"$1\"','        sudo dos2unix /vagrant/scripts/serve-apache.sh','        sudo bash /vagrant/scripts/serve-apache.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','    else','        echo \"Error: missing required parameters.\"','        echo \"Usage: \"','        echo \"  serve-apache domain path\"','function serve-laravel() {','        sudo dos2unix /vagrant/scripts/serve-laravel.sh','        sudo bash /vagrant/scripts/serve-laravel.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve domain path\"','function serve-proxy() {','        sudo dos2unix /vagrant/scripts/serve-proxy.sh','        sudo bash /vagrant/scripts/serve-proxy.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-proxy domain port\"','function serve-silverstripe() {','        sudo dos2unix /vagrant/scripts/serve-silverstripe.sh','        sudo bash /vagrant/scripts/serve-silverstripe.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-silverstripe domain path\"','function serve-spa() {','  if [[ \"$1\" && \"$2\" ]]','  then','    sudo bash /vagrant/scripts/create-certificate.sh \"$1\"','    sudo dos2unix /vagrant/scripts/serve-spa.sh','    sudo bash /vagrant/scripts/serve-spa.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','  else','    echo \"Error: missing required parameters.\"','    echo \"Usage: \"','    echo \"  serve-spa domain path\"','  fi','function serve-statamic() {','        sudo dos2unix /vagrant/scripts/serve-statamic.sh','        sudo bash /vagrant/scripts/serve-statamic.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-statamic domain path\"','function serve-symfony2() {','        sudo dos2unix /vagrant/scripts/serve-symfony2.sh','        sudo bash /vagrant/scripts/serve-symfony2.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-symfony2 domain path\"','function serve-symfony4() {','        sudo dos2unix /vagrant/scripts/serve-symfony4.sh','        sudo bash /vagrant/scripts/serve-symfony4.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-symfony4 domain path\"','function serve-pimcore() {','        sudo dos2unix /vagrant/scripts/serve-pimcore.sh','        sudo bash /vagrant/scripts/serve-pimcore.sh \"$1\" \"$2\" 80 443 \"${3:-7.1}\"','        echo \"  serve-pimcore domain path\"','function share() {','    if [[ \"$1\" ]]','        ngrok http ${@:2} -host-header=\"$1\" 80','        echo \"  share domain\"','        echo \"Invocation with extra params passed directly to ngrok\"','        echo \"  share domain -region=eu -subdomain=test1234\"','function flip() {','    sudo bash /vagrant/scripts/flip-webserver.sh','function __has_pv() {','    $(hash pv 2>/dev/null);','    return $?','function __pv_install_message() {','    if ! __has_pv; then','        echo $1','        echo \"Install pv with \\`sudo apt-get install -y pv\\` then run this command again.\"','        echo \"\"','function dbexport() {','    FILE=${1:-/vagrant/mysqldump.sql.gz}','    # This gives an estimate of the size of the SQL file','    # It appears that 80% is a good approximation of','    # the ratio of estimated size to actual size','    SIZE_QUERY=\"select ceil(sum(data_length) * 0.8) as size from information_schema.TABLES\"','    __pv_install_message \"Want to see export progress?\"','    echo \"Exporting databases to \'$FILE\'\"','    if __has_pv; then','        ADJUSTED_SIZE=$(mysql --vertical -uhomestead -psecret -e \"$SIZE_QUERY\" 2>/dev/null | grep \'size\' | awk \'{print $2}\')','        HUMAN_READABLE_SIZE=$(numfmt --to=iec-i --suffix=B --format=\"%.3f\" $ADJUSTED_SIZE)','        echo \"Estimated uncompressed size: $HUMAN_READABLE_SIZE\"','        mysqldump -uhomestead -psecret --all-databases --skip-lock-tables 2>/dev/null | pv  --size=$ADJUSTED_SIZE | gzip > \"$FILE\"','        mysqldump -uhomestead -psecret --all-databases --skip-lock-tables 2>/dev/null | gzip > \"$FILE\"','    echo \"Done.\"','function dbimport() {','    __pv_install_message \"Want to see import progress?\"','    echo \"Importing databases from \'$FILE\'\"','        pv \"$FILE\" --progress --eta | zcat | mysql -uhomestead -psecret 2>/dev/null','        cat \"$FILE\" | zcat | mysql -uhomestead -psecret 2>/dev/null','function xphp() {','    (php -m | grep -q xdebug)','    if [[ $? -eq 0 ]]','        XDEBUG_ENABLED=true','        XDEBUG_ENABLED=false','    if ! $XDEBUG_ENABLED; then xon; fi','    php \\','        -dxdebug.remote_host=192.168.10.1 \\','        -dxdebug.remote_autostart=1 \\','$@','    if ! $XDEBUG_ENABLED; then xoff; fi') )
					GROUP BY mpro."id", mpro."siteid", mpro."typeid", mpro."code",
						mpro."label", mpro."config", mpro."start", mpro."end",
						mpro."status", mpro."ctime", mpro."mtime", mpro."editor",
						mpro."target"
						
					
					LIMIT 133 OFFSET 0
				#0 /home/vagrant/code/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(69): Aimeos\Controller\Jobs\Product\Import\Csv\Standard->run()
#1 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\{closure}(Object(Aimeos\MShop\Context\Item\Standard), Object(Aimeos\Bootstrap), 'product/import/...')
#2 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(171): call_user_func_array(Object(Closure), Array)
#3 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(111): Aimeos\MW\Process\Pcntl->exec(Object(Closure), Array)
#4 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(208): Aimeos\MW\Process\Pcntl->start(Object(Closure), Array, false)
#5 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(128): Aimeos\MW\Process\Pcntl->waitOne()
#6 /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Decorator/Check.php(78): Aimeos\MW\Process\Pcntl->wait()
#7 /home/vagrant/code/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(76): Aimeos\MW\Process\Decorator\Check->wait()
#8 [internal function]: Aimeos\Shop\Command\JobsCommand->handle()
#9 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#12 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#13 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(184): Illuminate\Container\Container->call(Array)
#14 /home/vagrant/code/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(171): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /home/vagrant/code/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/vagrant/code/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Aimeos\Shop\Command\JobsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/vagrant/code/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/code/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main}
   Aimeos\MW\Process\Exception  : Process (PID "8492") failed with status "256"

  at /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php:205
    201| 
    202| 		if( $status > 0 )
    203| 		{
    204| 			if( $restart === false ) {
  > 205| 				throw new Exception( sprintf( 'Process (PID "%1$s") failed with status "%2$s"', $pid, $status ) );
    206| 			}
    207| 
    208| 			$this->start( $fcn, $data, false );
    209| 		}

  Exception trace:

  1   Aimeos\MW\Process\Pcntl::waitOne()
      /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php:128

  2   Aimeos\MW\Process\Pcntl::wait()
      /home/vagrant/code/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Decorator/Check.php:78

  Please use the argument -v to see more details.
````

**Comment by aimeos** [comment]
Remove the `catalog/import/csv` and `product/import/csv` jobs from your list. They need some configuration first before you can use them.

**Comment by Quix0r** [comment]
Done here. Yet still I find it confusing having an SQL error (lowest layer error) because of missing configuration. Better should be to check in higher methods if configuration is complete and in case of missing/example config entries, throw an exception to notify the user properly.

**Comment by aimeos** [comment]
You are right, that looks like an overuse of default settings. Is changed now:
https://github.com/aimeos/ai-controller-jobs/commit/2b9f515041c8289778bf9abf17f54c726469e9c9

**Comment by Quix0r** [comment]
Thank you. :-)
