### ISSUE TITLE
Route [aimeos_shop_terms] not defined.

### ISSUE THREAD

**Issue by mailnike** [aimeos/aimeos-laravel#278]
**Environment**
1. Version (e.g. 2017.10) - latest
2. Operating system (Linux, Mac, Windows) - Ubuntu

**Describe the bug**

Hi, once we go to 5. summary tab - it shows an error "A non-recoverable error occurred"

and in the table "madmin_log", error log says - "Route [aimeos_shop_terms] not defined.". 

```
#0 /Users/nikhil/Downloads/HomesteadCode/Laravel/ext/ai-laravel/lib/custom/src/MW/View/Helper/Url/Laravel5.php(61): Illuminate\Routing\UrlGenerator->route('aimeos_shop_ter...', Array, false)
#1 [internal function]: Aimeos\MW\View\Helper\Url\Laravel5->transform('aimeos_shop_ter...', NULL, NULL, Array, Array, Array)
#2 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(88): call_user_func_array(Array, Array)
#3 /Users/nikhil/Downloads/HomesteadCode/Laravel/ext/ai-client-html/client/html/templates/checkout/standard/option-partial-standard.php(84): Aimeos\MW\View\Standard->__call('url', Array)
#4 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(255): include('/Users/nikhil/D...')
#5 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(237): Aimeos\MW\View\Standard->includeFile('/Users/nikhil/D...')
#6 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Helper/Partial/Standard.php(36): Aimeos\MW\View\Standard->render('checkout/standa...')
#7 [internal function]: Aimeos\MW\View\Helper\Partial\Standard->transform('checkout/standa...', Array)
#8 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(88): call_user_func_array(Array, Array)
#9 /Users/nikhil/Downloads/HomesteadCode/Laravel/ext/ai-client-html/client/html/templates/checkout/standard/summary-body-standard.php(206): Aimeos\MW\View\Standard->__call('partial', Array)
#10 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(255): include('/Users/nikhil/D...')
#11 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(237): Aimeos\MW\View\Standard->includeFile('/Users/nikhil/D...')
#12 /Users/nikhil/Downloads/HomesteadCode/Laravel/ext/ai-client-html/client/html/src/Client/Html/Checkout/Standard/Summary/Standard.php(111): Aimeos\MW\View\Standard->render('checkout/standa...')
#13 /Users/nikhil/Downloads/HomesteadCode/Laravel/ext/ai-client-html/client/html/src/Client/Html/Checkout/Standard/Standard.php(137): Aimeos\Client\Html\Checkout\Standard\Summary\Standard->getBody('')
#14 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Controller/CheckoutController.php(53): Aimeos\Client\Html\Checkout\Standard\Standard->getBody()
#15 [internal function]: Aimeos\Shop\Controller\CheckoutController->indexAction('default', 'summary')
#16 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#17 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('indexAction', Array)
#18 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Aimeos\Shop\Controller\CheckoutController), 'indexAction')
#19 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#20 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Route->run()
#21 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/spark-aurelius/src/Http/Middleware/CreateFreshApiToken.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\Spark\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#47 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#49 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#73 /Users/nikhil/Downloads/HomesteadCode/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#74 /Users/nikhil/Downloads/HomesteadCode/Laravel/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#75 /Users/nikhil/.composer/vendor/laravel/valet/server.php(158): require('/Users/nikhil/D...')
#76 {main}

```

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/22786232/59043239-81c42500-8899-11e9-9d0e-09bcb399b587.png)

**Additional context**

Tried to add below routes in shop.php but still didn't work

```
        'terms_and_conditions' => ['prefix' => '{site?}/terms_and_conditions', 'middleware' => ['web']],
        'terms' => ['prefix' => '{site?}/terms', 'middleware' => ['web']],
```

**Comment by aimeos** [comment]
Can you please post the output of `./artisan route:list`?

**Comment by mailnike** [comment]
Here you go -


```
+--------+---------------+---------------------------------------------------------------------------+------------------------------+------------------------------------------------------------------------+------------------------------------------------------+
| Domain | Method        | URI                                                                       | Name                         | Action                                                                 | Middleware                                           |
+--------+---------------+---------------------------------------------------------------------------+------------------------------+------------------------------------------------------------------------+------------------------------------------------------+
|        | GET|HEAD      | /                                                                         |                              | Closure                                                                | web                                                  |
|        | GET|HEAD      | _debugbar/assets/javascript                                               | debugbar.assets.js           | Barryvdh\Debugbar\Controllers\AssetController@js                       | Barryvdh\Debugbar\Middleware\DebugbarEnabled,Closure |
|        | GET|HEAD      | _debugbar/assets/stylesheets                                              | debugbar.assets.css          | Barryvdh\Debugbar\Controllers\AssetController@css                      | Barryvdh\Debugbar\Middleware\DebugbarEnabled,Closure |
|        | DELETE        | _debugbar/cache/{key}/{tags?}                                             | debugbar.cache.delete        | Barryvdh\Debugbar\Controllers\CacheController@delete                   | Barryvdh\Debugbar\Middleware\DebugbarEnabled,Closure |
|        | GET|HEAD      | _debugbar/clockwork/{id}                                                  | debugbar.clockwork           | Barryvdh\Debugbar\Controllers\OpenHandlerController@clockwork          | Barryvdh\Debugbar\Middleware\DebugbarEnabled,Closure |
|        | GET|HEAD      | _debugbar/open                                                            | debugbar.openhandler         | Barryvdh\Debugbar\Controllers\OpenHandlerController@handle             | Barryvdh\Debugbar\Middleware\DebugbarEnabled,Closure |
|        | GET|HEAD      | _debugbar/telescope/{id}                                                  | debugbar.telescope           | Barryvdh\Debugbar\Controllers\TelescopeController@show                 | Barryvdh\Debugbar\Middleware\DebugbarEnabled,Closure |
|        | GET|HEAD      | admin                                                                     | aimeos_shop_admin            | Aimeos\Shop\Controller\AdminController@indexAction                     | web                                                  |
|        | GET|POST|HEAD | admin/{site}/jqadm/copy/{resource}/{id}                                   | aimeos_shop_jqadm_copy       | Aimeos\Shop\Controller\JqadmController@copyAction                      | web,auth                                             |
|        | GET|POST|HEAD | admin/{site}/jqadm/create/{resource}                                      | aimeos_shop_jqadm_create     | Aimeos\Shop\Controller\JqadmController@createAction                    | web,auth                                             |
|        | GET|POST|HEAD | admin/{site}/jqadm/delete/{resource}/{id}                                 | aimeos_shop_jqadm_delete     | Aimeos\Shop\Controller\JqadmController@deleteAction                    | web,auth                                             |
|        | GET|POST|HEAD | admin/{site}/jqadm/export/{resource}                                      | aimeos_shop_jqadm_export     | Aimeos\Shop\Controller\JqadmController@exportAction                    | web,auth                                             |
|        | GET|HEAD      | admin/{site}/jqadm/file/{type}                                            | aimeos_shop_jqadm_file       | Aimeos\Shop\Controller\JqadmController@fileAction                      | web,auth                                             |
|        | GET|HEAD      | admin/{site}/jqadm/get/{resource}/{id}                                    | aimeos_shop_jqadm_get        | Aimeos\Shop\Controller\JqadmController@getAction                       | web,auth                                             |
|        | POST          | admin/{site}/jqadm/save/{resource}                                        | aimeos_shop_jqadm_save       | Aimeos\Shop\Controller\JqadmController@saveAction                      | web,auth                                             |
|        | GET|POST|HEAD | admin/{site}/jqadm/search/{resource}                                      | aimeos_shop_jqadm_search     | Aimeos\Shop\Controller\JqadmController@searchAction                    | web,auth                                             |
|        | OPTIONS       | admin/{site}/jsonadm/{resource?}                                          | aimeos_shop_jsonadm_options  | Aimeos\Shop\Controller\JsonadmController@optionsAction                 | web,auth                                             |
|        | PUT           | admin/{site}/jsonadm/{resource}/{id?}                                     | aimeos_shop_jsonadm_put      | Aimeos\Shop\Controller\JsonadmController@putAction                     | web,auth                                             |
|        | POST          | admin/{site}/jsonadm/{resource}/{id?}                                     | aimeos_shop_jsonadm_post     | Aimeos\Shop\Controller\JsonadmController@postAction                    | web,auth                                             |
|        | PATCH         | admin/{site}/jsonadm/{resource}/{id?}                                     | aimeos_shop_jsonadm_patch    | Aimeos\Shop\Controller\JsonadmController@patchAction                   | web,auth                                             |
|        | GET|HEAD      | admin/{site}/jsonadm/{resource}/{id?}                                     | aimeos_shop_jsonadm_get      | Aimeos\Shop\Controller\JsonadmController@getAction                     | web,auth                                             |
|        | DELETE        | admin/{site}/jsonadm/{resource}/{id?}                                     | aimeos_shop_jsonadm_delete   | Aimeos\Shop\Controller\JsonadmController@deleteAction                  | web,auth                                             |
|        | GET|HEAD      | api/user                                                                  |                              | Closure                                                                | api,auth:api                                         |
|        | GET|POST|HEAD | basket                                                                    | aimeos_shop_basket           | Aimeos\Shop\Controller\BasketController@indexAction                    | web                                                  |
|        | GET|POST|HEAD | checkout/{c_step?}                                                        | aimeos_shop_checkout         | Aimeos\Shop\Controller\CheckoutController@indexAction                  | web                                                  |
|        | GET|POST|HEAD | confirm/{code?}                                                           | aimeos_shop_confirm          | Aimeos\Shop\Controller\CheckoutController@confirmAction                | web                                                  |
|        | GET|POST|HEAD | count                                                                     | aimeos_shop_count            | Aimeos\Shop\Controller\CatalogController@countAction                   | web                                                  |
|        | GET|POST|HEAD | detail/pin/{pin_action?}/{pin_id?}/{d_prodid?}/{d_name?}/{d_pos?}         | aimeos_shop_session_pinned   | Aimeos\Shop\Controller\CatalogController@detailAction                  | web                                                  |
|        | GET|POST|HEAD | detail/{d_prodid}/{d_name?}/{d_pos?}                                      | aimeos_shop_detail           | Aimeos\Shop\Controller\CatalogController@detailAction                  | web                                                  |
|        | GET|HEAD      | home                                                                      | home                         | App\Http\Controllers\HomeController@index                              | web,auth                                             |
|        | OPTIONS       | jsonapi/{resource?}                                                       | aimeos_shop_jsonapi_options  | Aimeos\Shop\Controller\JsonapiController@optionsAction                 | web,api                                              |
|        | DELETE        | jsonapi/{resource}                                                        | aimeos_shop_jsonapi_delete   | Aimeos\Shop\Controller\JsonapiController@deleteAction                  | web,api                                              |
|        | GET|HEAD      | jsonapi/{resource}                                                        | aimeos_shop_jsonapi_get      | Aimeos\Shop\Controller\JsonapiController@getAction                     | web,api                                              |
|        | PATCH         | jsonapi/{resource}                                                        | aimeos_shop_jsonapi_patch    | Aimeos\Shop\Controller\JsonapiController@patchAction                   | web,api                                              |
|        | PUT           | jsonapi/{resource}                                                        | aimeos_shop_jsonapi_put      | Aimeos\Shop\Controller\JsonapiController@putAction                     | web,api                                              |
|        | POST          | jsonapi/{resource}                                                        | aimeos_shop_jsonapi_post     | Aimeos\Shop\Controller\JsonapiController@postAction                    | web,api                                              |
|        | GET|POST|HEAD | list                                                                      | aimeos_shop_list             | Aimeos\Shop\Controller\CatalogController@listAction                    | web                                                  |
|        | POST          | login                                                                     |                              | App\Http\Controllers\Auth\LoginController@login                        | web,guest                                            |
|        | GET|HEAD      | login                                                                     | login                        | App\Http\Controllers\Auth\LoginController@showLoginForm                | web,guest                                            |
|        | POST          | logout                                                                    | logout                       | App\Http\Controllers\Auth\LoginController@logout                       | web                                                  |
|        | GET|POST|HEAD | myaccount                                                                 | aimeos_shop_account          | Aimeos\Shop\Controller\AccountController@indexAction                   | web,auth                                             |
|        | GET|POST|HEAD | myaccount/download/{dl_id}                                                | aimeos_shop_account_download | Aimeos\Shop\Controller\AccountController@downloadAction                | web,auth                                             |
|        | GET|POST|HEAD | myaccount/favorite/{fav_action?}/{fav_id?}/{d_prodid?}/{d_name?}/{d_pos?} | aimeos_shop_account_favorite | Aimeos\Shop\Controller\AccountController@indexAction                   | web,auth                                             |
|        | GET|POST|HEAD | myaccount/watch/{wat_action?}/{wat_id?}/{d_prodid?}/{d_name?}/{d_pos?}    | aimeos_shop_account_watch    | Aimeos\Shop\Controller\AccountController@indexAction                   | web,auth                                             |
|        | POST          | password/email                                                            | password.email               | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail  | web,guest                                            |
|        | GET|HEAD      | password/reset                                                            | password.request             | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm | web,guest                                            |
|        | POST          | password/reset                                                            |                              | App\Http\Controllers\Auth\ResetPasswordController@reset                | web,guest                                            |
|        | GET|HEAD      | password/reset/{token}                                                    | password.reset               | App\Http\Controllers\Auth\ResetPasswordController@showResetForm        | web,guest                                            |
|        | GET|HEAD      | privacy                                                                   | aimeos_shop_privacy          | Aimeos\Shop\Controller\PageController@privacyAction                    |                                                      |
|        | GET|HEAD      | register                                                                  | register                     | App\Http\Controllers\Auth\RegisterController@showRegistrationForm      | web,guest                                            |
|        | POST          | register                                                                  |                              | App\Http\Controllers\Auth\RegisterController@register                  | web,guest                                            |
|        | GET|POST|HEAD | stock                                                                     | aimeos_shop_stock            | Aimeos\Shop\Controller\CatalogController@stockAction                   | web                                                  |
|        | GET|POST|HEAD | suggest                                                                   | aimeos_shop_suggest          | Aimeos\Shop\Controller\CatalogController@suggestAction                 | web                                                  |
|        | GET|HEAD      | terms                                                                     | aimeos_shop_terms            | Aimeos\Shop\Controller\PageController@termsAction                      |                                                      |
|        | GET|POST|HEAD | update                                                                    | aimeos_shop_update           | Aimeos\Shop\Controller\CheckoutController@updateAction                 |                                                      |
+--------+---------------+---------------------------------------------------------------------------+------------------------------+------------------------------------------------------------------------+------------------------------------------------------+
```

**Comment by aimeos** [comment]
The `aimeos_shop_terms` route for `/terms` is there. Can you access `http://127.0.0.1:8000/terms`?
Can you also post your ./config/shop.php file?
