### ISSUE TITLE
Datatype mismatch on Users - bigint vs uuid

### ISSUE THREAD

**Issue by PharaohAsh** [aimeos/aimeos-laravel#515]
**Environment**
1. `"aimeos/aimeos-laravel": "~2024.10"`
2. Operating system = Mac
3. DB = Postgresql

**Describe the bug**
My Users table is using UUIDs for its primary key.
I am unable to continue with the `artisan aimeos:setup` step.

**To Reproduce**
1. Have an existing Laravel project
2. Users table uses [UUIDs](https://laravel.com/docs/11.x/eloquent#uuid-and-ulid-keys) as a primary key
4. Run `php artisan aimeos:setup`

**Expected behavior**
It should install and set up aimeos using the user defined type.

**Screenshots**

**Additional context**
```
...
Migrating: vendor/aimeos/ai-laravel/setup/CustomerRenameGroupLaravel.php
Migrated:  vendor/aimeos/ai-laravel/setup/CustomerRenameGroupLaravel.php (154.37ms)
Migrating: vendor/aimeos/aimeos-core/setup/Customer.php

   Doctrine\DBAL\Exception\DriverException 

  An exception occurred while executing a query: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  foreign key constraint "fk_lvupr_pid" cannot be implemented
DETAIL:  Key columns "parentid" and "id" are of incompatible types: bigint and uuid.

  at vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:80
     76▕             case '08006':
     77▕                 return new ConnectionException($exception, $query);
     78▕         }
     79▕ 
  ➜  80▕         return new DriverException($exception, $query);
     81▕     }
     82▕ }
     83▕ 

      +26 vendor frames 

  27  artisan:13
      Illuminate\Foundation\Application::handleCommand()

```
```
[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  foreign key constraint \"fk_lvupr_pid\" cannot be implemented
DETAIL:  Key columns \"parentid\" and \"id\" are of incompatible types: bigint and uuid. at /var/www/html/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(33): Doctrine\\DBAL\\Driver\\PDO\\Exception::new()
#1 /var/www/html/vendor/doctrine/dbal/src/Connection.php(878): Doctrine\\DBAL\\Driver\\PDO\\Connection->exec()
#2 /var/www/html/vendor/aimeos/upscheme/src/Schema/DB.php(826): Doctrine\\DBAL\\Connection->executeStatement()
#3 /var/www/html/vendor/aimeos/upscheme/src/Up.php(367): Aimeos\\Upscheme\\Schema\\DB->up()
#4 /var/www/html/vendor/aimeos/upscheme/src/Up.php(191): Aimeos\\Upscheme\\Up->runTasks()
#5 /var/www/html/vendor/aimeos/aimeos-core/Setup.php(84): Aimeos\\Upscheme\\Up->up()
#6 /var/www/html/vendor/aimeos/aimeos-laravel/src/Command/SetupCommand.php(65): Aimeos\\Setup->up()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Aimeos\\Shop\\Command\\SetupCommand->handle()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 /var/www/html/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#21 {main}
```

**Comment by aimeos** [comment]
You need to overwrite the Aimeos definitions of the `parentid` columns in the `users_list` and `users_property` columns:
1.) Create and install an Aimeos extension for your project (https://aimeos.org/extensions)
2.) Add a ./packages/<your-extension>/setup/default/schema/customer.php file to your extension
3.) Use this as content for the file:
```
<?php
return [
  'table' => [
    'users_list' => function( \Aimeos\Upscheme\Schema\Table $table ) {
        $table->uuid(  'parentid' );
    },
    'users_property' => function( \Aimeos\Upscheme\Schema\Table $table ) {
        $table->uuid(  'parentid' );
    },
  ],
];
```
See also: https://aimeos.org/docs/latest/infrastructure/schema-migrations/#modify-existing-tables

**Comment by PharaohAsh** [comment]
Gotcha, ta!
